# Generated by Django 2.2.2 on 2019-06-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('months_available', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('shadow', models.CharField(default='small', max_length=255)),
                ('location', models.CharField(default='river', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
