# Generated by Django 2.2.2 on 2019-06-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_auto_20190613_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='months_available',
            field=models.CharField(default='All year', max_length=255),
        ),
    ]
